libxkbfile: Autospec creation for update from version 1.1.2 to version 1.1.3
Alan Coopersmith (13):
      configure: Use LT_INIT from libtool 2 instead of deprecated AC_PROG_LIBTOOL
      Set close-on-exec when opening files
      _XkbMakeAtom: remove check for impossible case
      _XkbInitAtoms: check for malloc() failure
      XkbChangeAtomDisplay: stop leaking atom name
      XkbCFReportError: avoid -Wformat-nonliteral warning
      XkbWriteCFile: stop leaking header file ifdef name
      DefaultParser: avoid -Wimplicit-fallthrough warnings
      xkbtext.c: Add tbGetBufferString helper function
      XkbIndentText: Fix -Wsign-compare warning
      Fix -Wsign-compare warnings in xkbtext.c & xkmread.c
      Add a meson build system
      libxkbfile 1.1.3